### ISSUE TITLE
@composite strategy

### ISSUE THREAD

**Issue by flyingmutant** [AltSysrq/proptest#1]
As a huge fan of Hypothesis — thanks a lot for making this, fantastic work!

Am I correct that there is no support for [@composite](https://hypothesis.readthedocs.io/en/latest/data.html#composite-strategies) strategy yet?

**Comment by AltSysrq** [comment]
Thanks for the feedback! It looks like you're correct about `@composite`. I originally thought that was equivalent to `.prop_map()`, but now I see it isn't and it does sound useful and it would actually simplify some of the code I have. I'll see what I can do.

**Comment by AltSysrq** [comment]
Version 0.2.0 now has [`prop_flat_map()`](https://docs.rs/proptest/0.2.0/proptest/strategy/trait.Strategy.html#method.prop_flat_map), which was the main missing piece to being able to do the same things. There's also a [`prop_compose!`](https://docs.rs/proptest/0.2.0/proptest/macro.prop_compose.html) macro that's sort of like `@composite`, though less flexible since proptest uses static composition rather than Hypothesis' dynamic composition. While the macro is a bit limited, I do believe you can get everything `@composite` gets you by using the combinators directly, albeit less ergonomically.

Please feel free to reopen/update this issue if you think something's still missing.
