### ISSUE TITLE
[Breaking] Update the rand to v0.6.0

### ISSUE THREAD

**Issue by Centril** [AltSysrq/proptest#107]
Rand version 0.6.0, https://rust-random.github.io/book/update-0.6.html, has been released so we should presumably upgrade to that version in the next breaking change to proptest since rand is a public dependency of proptest.

**Comment by Centril** [comment]
Also... do we want to change from `XorShiftRng` to something else at this point (maybe @dhardy can say something about the appropriateness of various RNGs for property based testing...)?

Can we change it given that we store seeds?
Do we guarantee the stability of stored seeds over breaking changes?

**Comment by dhardy** [comment]
I don't know enough about what you want here — do you depend on high-quality generators or not care much? Do you care greatly about reproducibility? Do you seed RNGs from other RNGs?

**Comment by AltSysrq** [comment]
> Can we change it given that we store seeds?

The persistence file does indicate which RNG was used, so if we really wanted to we'd just need to make a façade or something that would allow having mulitple backing implementations.

> uality is also good so that proptest can test more inputs

According to [Wikipedia](https://en.wikipedia.org/wiki/Xorshift), the period of XorShift is 2**128-1 (measured in output `u32`s) so I don't see exhausting the available search space to be a realistic concern. It also passes quite a few statistical tests, so I'm not sure if there are any cases where the testing process would be adversely affected by RNG quality issues.

**Comment by dhardy** [comment]
> If we can have performance and quality that would be nicest of course ;)

Maybe [Xoshiro**](https://github.com/rust-random/book/pull/5) would be well suited to you. The exact "quality" gets debated because these small-fast-RNGs aren't cryptographic so there is usually some way to design a test which breaks them, but it's a pretty good generator I think. `Pcg64Mcg` is also quite fast on 64-bit hardware. Actually, if you want reproducibility and you're targeting both 32-bit and 64-bit hardware then you have to compromise.

> The persistence file does indicate which RNG was used, so if we really wanted to we'd just need to make a façade or something that would allow having mulitple backing implementations.

This may give you a way around that then — recommend using a different RNG on 32-bit platforms, for example.

Run the Rand benches with `cargo bench --bench generators`.

> I think so yes.

Then you can't just change at will, and shouldn't use `SmallRng`.

> Yes.

*Please* don't do this with Xorshift. It can literally just create a copy of itself (with a small offset). Most other RNGs are good enough not to have this problem.

Your current `Seed` is 128-bit; several other generators use the same seed size.

**Comment by vks** [comment]
@AltSysrq 
> We perturb the key to prevent exactly that. Though in retrospect using XOR to perturb a XOR-based generator probably wasn't the best choice.

Another approach (favored by Vigna et al.) is to use a very different RNG algorithm for seeding.

**Comment by AltSysrq** [comment]
This `rand` upgrade occurred in proptest 0.9.0 via https://github.com/AltSysrq/proptest/pull/113
