### ISSUE TITLE
Taking Fn vs FnMut closures (e.g. prop_map)

### ISSUE THREAD

**Issue by aldanor** [AltSysrq/proptest#115]
In methods like `prop_map()`, is there a reason for taking an `Fn` and not an `FnMut` closure? In some cases (e.g. when you use an external mutable generator for parts where you don't care for shrinking and other fancy stuff) this enforces the user to `Rc<RefCell<>>` everything that's captured and needs to be mutated:

https://github.com/AltSysrq/proptest/blob/9119682a19607f7cec9135b1e06ebe64236b5596/src/strategy/traits.rs#L71-L76

**Comment by Centril** [comment]
Can you elaborate on your use-case?

You might want to look at how the [`shrinking`](https://github.com/AltSysrq/proptest/blob/master/src/test_runner/runner.rs#L587-L671) logic is implemented; in particular, because testing functions are `impl Fn(<V as ValueTree>::Value) -> TestCaseResult` the `.current()` method of `V` may be called more than once; the first time for providing the `Value` to the tester and the [second time](https://github.com/AltSysrq/proptest/blob/master/src/test_runner/runner.rs#L578) for providing the final counterexample which is then displayed.

This means that if your definition of `.current()` doesn't stay the same if you call the function successively without simplifying/complicating in between, then the results can become inconsistent.

Furthermore, since the signature of `current` is `fn(&self) -> Self::Value` this means that an `FnMut` closure shouldn't be usable in any case since you'd need `current` to have the signature `fn(&mut self) -> Self::Value` instead. `Arc` doesn't help either. The other way through would be to use some interior mutability a la `Mutex`; but the benefit doesn't seem to outweigh the cost.

**Comment by AltSysrq** [comment]
To elaborate on @Centril's points a bit further, proptest is pretty strongly built on the assumption that value generators are pure from an external perspective, something a mutating function would in almost all cases violate.

Using an externally impure function in `prop_map` will likely lead to erratic behaviour at best. In particular, not only will shrinking be unable to find the correct value reliably, it can actually cause it to converge on an input that the test _passes_. Other features like test case persistence and forked tests also rely on purity.

**Comment by Centril** [comment]
@AltSysrq We might want to ramp up the documentation on this front; I don't think [`ValueTree`'s documentation](https://altsysrq.github.io/rustdoc/proptest/latest/proptest/strategy/trait.ValueTree.html#tymethod.current) says that sufficiently clearly at the moment. Adding docs in other places might also be good (e.g. somewhere prominent in the new book...).

**Comment by AltSysrq** [comment]
0.9.0 includes explicit documentation about this for `prop_map`. It might be worth expanding in the future but this at least answers the immediate question.
