### ISSUE TITLE
Union value tree creation has quadratic time complexity in the number of variants

### ISSUE THREAD

**Issue by sunshowers** [AltSysrq/proptest#143]
We've been running into some performance issues with large enums and proptest. I did some digging in and it looks like value tree creation is quadratic time in the number of variants involved. That's because value trees are also generated for all previous variants.

For example, for a union with variants 0 through 20, if variant 10 is picked, value trees are generated for all variants 0 through 9 (both inclusive) as well.

Ideally, the value tree generation for variants 0 through 9 would be deferred to shrinking time. I looked at a few approaches on how to do this, and it seems like all of them would require a breaking API change and some of them would require new Rust features:

* Stash away the `&mut TestRunner` into a hypothetical `LazyValueTree` structure. This would require the value tree to carry around a lifetime parameter, and would also require GATs for the `Strategy` trait's `Tree` associated type.
* Do the same as above, except avoid the lifetime parameter by using `Rc` or `Arc` for the test runner. Not great.
* Use a lazy structure, but pass the test runner into `simplify` and `complicate` and use that to initialize the child value trees lazily. This seems like the simplest way forward but it is a major API change and I'm not sure what the other consequences here are.

What do you think?

**Comment by sunshowers** [comment]
Another option that occurred to me, and wouldn't require an API change -- add a way to disable shrinking across enum variants. That would mean that value trees don't need to be generated for any previous variants.

**Comment by sunshowers** [comment]
One more option that might not cause an API breakage would be to add methods `simplify_with_runner` and `complicate_with_runner` to ValueTree. Switch the shrinking code to always use these impls, provide default impls that call into the `simplify` and `complicate` methods, and make the union value trees use the new methods and panic with the old methods.

**Comment by sunshowers** [comment]
Ahh, whoops I was wrong :) some combinators already stash the test runner locally so we can just follow that pattern. Thanks :)

**Comment by sunshowers** [comment]
Ah, sorry again. Looks like the variant strategies need to be stashed away in the lazy value tree as well for this to work. Since strategies aren't always `Clone` this is pretty hard to do. We could `Arc` all the variant strategies, but that would add a runtime cost (but maybe that's an OK tradeoff? But if a strategy is already `BoxedStrategy`, it would lead to double-arcing.)

I'm happy to implement this but I'd love some advice on how to go forward here :) thanks!

**Comment by AltSysrq** [comment]
I've never really been happy with the way `Union` works either. The issue here is also a major contributing factor to https://github.com/AltSysrq/proptest/issues/16.

> add a way to disable shrinking across union variants

This would actually be pretty easy to add. The various `Union` implementations could implement `fn no_shrink()` to set some flag in the `Union` itself indicating that generating the other variants is unnecessary.

> lazy structure

I do like this idea. I don't think I'd be too bothered about the extra level of `Arc`ing — the cost of the allocation and indirection is in most cases cheaper than generating the extra variants.

One thing to keep in mind if you do want to try to implement this yourself is that it needs to be deterministic regardless of the order the variants come into play (e.g. `new_tree(); current(); shrink(); current();` and `new_tree(); shrink(); current();` need to produce the same value in the end), which probably means creating all the forked RNGs for the earlier variants up-front, similar to how the current code generates the `ValueTree`s for all the earlier variants up-front. (Though of course there's still the benefit of not needing to recurse into the variants.)
