### ISSUE TITLE
Build fails in Rust 1.48.0 nightly

### ISSUE THREAD

**Issue by ekexium** [AltSysrq/proptest#209]
Build succeeds for rust 1.46.0 stable, but failed for Rust 1.48.0 nightly.
I'm using proptest 0.10.1 and proptest-derive 0.2.0.

Example:
```Rust
use proptest::{arbitrary::any_with, collection::size_range};
use proptest_derive::Arbitrary;
#[derive(Arbitrary)]
pub struct Key(
    #[proptest(strategy = "any_with::<Vec<u8>>((size_range(1024), ()))")]
    pub Vec<u8>,
);
```

Build error: 
```
❯ cargo build
   Compiling play v0.1.0 (/Users/ekexium/code/play)
error: [proptest_derive, E0026] during #[derive(Arbitrary)]:
The attribute modifier `strategy` inside `#[proptest(..)]` must have the format `#[proptest(strategy = "<expr>")]` where `<expr>` is a valid Rust expression. Please see: https://PATH/TO/foo#E0026 for more information.
 --> src/lib.rs:3:17
  |
3 | #[derive(Debug, Arbitrary)]
  |                 ^^^^^^^^^
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused imports: `arbitrary::any_with`, `collection::size_range`
 --> src/lib.rs:1:16
  |
1 | use proptest::{arbitrary::any_with, collection::size_range};
  |                ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

error: could not compile `play`.

To learn more, run the command again with --verbose.
```

Don't know if it's a bug. Do you have any idea?

**Comment by Centril** [comment]
Can you please paste the build error?

**Comment by ekexium** [comment]
> Can you please paste the build error?

Sorry I put the wrong content in build errors. It's Updated.

**Comment by Centril** [comment]
Odd. This error arises when `proptest_derive` gets a malformed expression, according to `syn`.
- Throws the error: https://github.com/AltSysrq/proptest/blob/a82973133a5d5ea5571a4bce075b6a9aa6c9f8c6/proptest-derive/src/attr.rs#L442
- Parses the expression: https://github.com/AltSysrq/proptest/blob/a82973133a5d5ea5571a4bce075b6a9aa6c9f8c6/proptest-derive/src/attr.rs#L437
- You'll end up here, which routes to `syn`'s `.parse()`: https://github.com/AltSysrq/proptest/blob/a82973133a5d5ea5571a4bce075b6a9aa6c9f8c6/proptest-derive/src/attr.rs#L569

The token stream `any_with::<Vec<u8>>((size_range(1024), ()))` is however definitely a well-formed Rust expression syntactically, unless there are issues in `rustc`'s pretty printing or so. Could you test whether `rustc` handles this right? The syn dependency shouldn't have been changed since we aren't using 1.0+ yet and 0.15.*. shouldn't have been changed.

**Comment by Centril** [comment]
Maybe caused by https://github.com/rust-lang/rust/issues/76399.

**Comment by ekexium** [comment]
Latest nightly doesn't have this problem
