### ISSUE TITLE
MSRV 1.50.0? 

### ISSUE THREAD

**Issue by clintfred** [AltSysrq/proptest#230]
Hi! Thanks for the awesome crate.

I see in the changelog for 1.0, you say 
> The minimum supported Rust version has been increased to 1.50.0.

I am one of the maintainers or recrypt.rs and our MSRV is 1.41.1. I was surprised to see that our use of proptest worked fine, so I thought I'd ask for a little more detail about the MSRV of 1.50.0. 
What requires 1.50? Or maybe you are just bumping it up to current without any particular need (which seems fine proptest is a testing tool)?

Would you expect versions less than 1.50.0 to continue to work?

Thanks again!

**Comment by AltSysrq** [comment]
Maybe this isn't the conventional interpretation, but the changelog is using "minimum supported Rust version" in the sense of stability guarantees rather than a literal statement that the code doesn't currently compile on older versions. In other words, the change is regarding what versions are actively tested against. In general, I've bumped the MSRV to the latest stable on any release that had breaking changes anyway to minimise the likelihood that there would need to be a breaking release later for _just_ the MSRV bump.

But perhaps that's too aggressive. As you've noticed, it doesn't actually require that version, so it would be possible to back the change off.

**Comment by Centril** [comment]
> But perhaps that's too aggressive.

I feel our current policy is good since it allows us to take advantage of recent language improvements. I'd prefer not changing anything here. Most Rust users do bump to the next stable compiler fairly soon. Supporting a year-old compiler does not seem necessary to me when doing a breaking release.

**Comment by clintfred** [comment]
I don't see a problem with bumping it, but it might discourage users that are trying to be very conscious of compiler compatibility. 

What I do on some of my crates is use a [build matrix in CI](https://github.com/IronCoreLabs/recrypt-rs/blob/8a15435132d10477183333c9d32925d78193e076/.github/workflows/ci.yaml#L94) and have one entry in the matrix be pinned to a specific version of `rustc` (in addition to `stable`, `beta`, or whatever). Then, as we're making changes, it is transparent to everyone when the minimum compiler version needs to be bumped. We've found it to be low effort once it's set up.

**Comment by AltSysrq** [comment]
Proptest's CI also has a [pinned version](https://github.com/AltSysrq/proptest/blob/master/.github/workflows/rust.yml#L26) to ensure that minor releases don't include an MSRV change.

**Comment by clintfred** [comment]
Sounds good. I'm going to close this issue. Thanks for the discussion.
