### ISSUE TITLE
Some form of deadline setting

### ISSUE THREAD

**Issue by Eh2406** [AltSysrq/proptest#41]
Hi, I am really excited to see your work on this project!

I was looking forward to using a deadline type feature to look for accidental infinite loops in some code. I know that [hypothesis as a deadline setting](https://hypothesis.readthedocs.io/en/latest/settings.html?highlight=deadline#hypothesis.settings.deadline). How hard is it to add it to this project?

**Comment by AltSysrq** [comment]
I would certainly love to have such a feature, having run into infinite loops with proptest myself. Unfortunately, I'm not sure that it's possible in the Rust test environment.

To separate the idea from proptest, imagine you had a function that would be called like

```rust
run_with_timeout_or_panic(5000 /* ms */, || {
    // do stuff...
});
```

which would panic if the closure didn't return within the timeout.

The closure would of course need to be run on a separate thread from whatever is timing it. The problem that arises is, if the timeout is passed, what do we do about that other thread?

Python is interpreted, so it can fairly easily support interrupting/terminating a compute-bound task without causing issues. We can't do that in a native environment; for example, the thread could be calling into `malloc` which may take a lock, and terminating the thread would leave the heap eternally locked.

`libcheck` gets around this by forking a new process and killing the process if it times out. This of course only works on Unix and also only works if the process has exactly one thread at the test runner level, but the rust test harness runs things in multiple threads. Making separate processes could potentially work with some kind of [custom test harness](https://github.com/rust-lang/rfcs/pull/2318) but right now doesn't seem possible.

The remaining option is to just abandon the thread and let it run, but since proptest could generate hundreds of test cases in the shrinking process, the resource contention would get pretty severe.

**Comment by AltSysrq** [comment]
I was thinking about this some more and I think this may be reasonably possible without needing to dive into any OS's esoterica.

The `proptest!` macro has enough information to determine the fully-qualified path to the test functions it produces, and `std::env` will give us the current executable and its arguments, which is sufficient to spawn another test runner process that runs only one particular test. Environment variables could be used to pass information to the child. To be able to run more than one test case in the child and avoid spawning too man processes, some IPC mechanism would be needed (since stdout/stderr are already in use) for the child to communicate what it does back to the parent.

Unless someone sees some reason this isn't a good approach, I'll probably start looking into this soon.

**Comment by AltSysrq** [comment]
Just a quick update on this: I've implemented [a crate](https://crates.io/crates/rusty-fork) for spawning sub-processes of tests this way, next up is integrating it into proptest.

**Comment by AltSysrq** [comment]
I finally got the whole thing working. This is [available](https://github.com/altsysrq/proptest#forking-and-timeouts) in 0.7.1.
