### ISSUE TITLE
Expanded example for prop_oneof macro

### ISSUE THREAD

**Issue by ornamentist** [AltSysrq/proptest#49]
The documentation for generating recursive data shows the use of the prop_oneof macro in that generating scenario--thanks!

Could we have a stand-alone example of using prop_oneof as the idiomatic way to choose from a group of strategies at run time?  As an example, suppose we have existing generators:

```
prop_compose! {
    [pub] fn small()(x in 0..100) -> u64 {
        // expression using x
    }
}

prop_compose! {
    [pub] fn medium()(x in 200..400) -> u64 {
        // expression using x
    }
}

prop_compose! {
    [pub] fn large()(x in 500..1000) -> u64 {
        // expression using x
    }
}
```

Then an example of the scaffolding needed to use 

```
prop_oneof![small(), medium(), large()]
```

in test functions as a `sized_any()` generator would be very useful. Apologies if this is not the right way to go about choosing generators at run-time.

**Comment by AltSysrq** [comment]
Happy to add more examples, but could you clarify what issue you're having that makes scaffolding seem necssary? Generally the invocation you showed above just works directly. For example, the following compiles and runs as desired:

```rust
    prop_compose! {
        fn small()(x in 0u64..100) -> u64 {
            x
        }
    }
    prop_compose! {
        fn medium()(x in 200u64..400) -> u64 {
            x
        }
    }
    prop_compose! {
        fn large()(x in 500u64..1000) -> u64 {
            x
        }
    }

    proptest! {
        #[test]
        fn do_something(_x in prop_oneof![small(), medium(), large()]) {
            // Test _x...
        }
    }
```

(I had to explicitly write `0u64` and such since otherwise rustc defaults the type to `i32`.)

Or by "choosing generators at run-time" are you perhaps looking for something where _your code_ chooses the generators?

**Comment by ornamentist** [comment]
Thanks for clarifying that -- I misunderstood the role of prop_oneof, assuming it needed "lifting" to the level of the others kinds of generators. I can see now there's not much point for a separate example.
