### ISSUE TITLE
regex generation tests same case multiple times

### ISSUE THREAD

**Issue by danburkert** [AltSysrq/proptest#70]
With the regex pattern `[a-z]{1, 5}` and the assertion that the output length is even, `proptest` will repeatedly test the same (original) value over and over as it shrinks/expands:

```
"saanf"
"aanf"
"saanf"
"sanf"
"saanf"
"sanf"
"saanf"
"saaf"
"saanf"
"saan"
"saanf"
"jaanf"
"eaanf"
"caanf"
"baanf"
"aaanf"
"aaagf"
"aaadf"
"aaabf"
"aaaaf"
"aaaac"
"aaaab"
"aaaaa"
```

Here's the test for context:

```rust
        #[test]
        fn test_string_shrink(s in "[a-z]{1, 5}") {
            use env_logger;
            let _ = env_logger::try_init();
            info!("{:?}");
            assert!(s.len() % 2 != 0);
        }
```

This also demonstrates the shrinking method used by `proptest` can get 'stuck' at a local minimum (in this case `aaaaa` instead of `a`) because it doesn't try shrinking more than one character at once.  This seems like a more difficult issue to fix, though.  Perhaps there's some literature on effective string shrinking strategies out there?

**Comment by AltSysrq** [comment]
> will repeatedly test the same (original) value over and over as it shrinks/expands:

This is an inevitable consequence of the design of proptest's shrinking process. In order to explore another simplification path, the shrinker must first return to a failing test case, which in your example means returning to the original input. It would be possible to redifine the `complicate()` step to avoid that, but IMO it's not worth the complexity to save a little time on failing tests.

> the shrinking method used by `proptest` can get 'stuck' at a local minimum

Indeed. This isn't unique to strings. Shrinking for essentially all types more complex than `bool` have this property. Finding _the_ simplest failing case in general has exponential complexity, so the shrinkers use heuristic approaches that run in linear time or less. In this case, the shrinker is built with the expectation that problematic strings are caused by individual characters or character sequences rather than the total length of the string, so it proceeds by deleting or simplifying characters one at a time.

**Comment by Eh2406** [comment]
Some context: I am working on a [complicated strategy](https://github.com/rust-lang/cargo/pull/5921) with [slow tests associated](https://github.com/rust-lang/cargo/pull/5921/files#diff-e4a53852638801c080290c10cd53e3dfR274) with it. The current implementation [filters out the parts of the generated input that doesn't make sense](https://github.com/rust-lang/cargo/pull/5921/files#diff-e4a53852638801c080290c10cd53e3dfR253). This means that shrinking takes a long time (several hours), and that the same input is fed to the tests many times (hundreds). A better strategy may fix this situation (suggestions welcome), but that is the context I am coming from.

I wonder whether we could have an *opt in* setting for the proptest macro that when shrinking would cache the inputs and whether the test passed so when an input is regenerated the test could get skipped.

**Comment by danburkert** [comment]
I ended up writing my own `String` and `Vec<u8>` shrinkers to work around this, as well as to tailor  shrinking to cases where the strings/byte strings are used as lexicographic keys.  You can find the code [here](https://github.com/danburkert/kudu-rs/blob/master/src/prop/string.rs) and [here](https://github.com/danburkert/kudu-rs/blob/master/src/prop/binary.rs).  I'd love to have it upstreamed into proptest proper, but realistically I don't have the time to do so myself.

**Comment by Eh2406** [comment]
`0.8.6` is just an amazing fount of features! Everything I needed, everything I asked for, everything I had made an offhand comment about, and some of the things I had only sort of thought might be worth suggesting.

**Comment by Eh2406** [comment]
Having now looked at a large number of shrink `HashSet<String>`, I'd love to have an alternative steiker that shrinks strings lexicographic, like how we have [bits module](https://altsysrq.github.io/rustdoc/proptest/latest/proptest/bits/index.html). Not that I have any ideas how to implement that.

**Comment by danburkert** [comment]
I’ve implemented it here:
https://github.com/danburkert/kudu-rs/blob/master/src/prop/string.rs.  Feel
free to take that and adapt as necessary.  There’s also a version for
binary in another module.

**Comment by Eh2406** [comment]
Yes that is a good start, I'd want it to have the regex interfase of the current string generators.
