### ISSUE TITLE
impl Strategy for Vec<impl Strategy>

### ISSUE THREAD

**Issue by Eh2406** [AltSysrq/proptest#85]
On IRC @Centril suggested that a function for turning a vec of strategies into a strategy for a vec of that size would help with [my work for cargo.](https://github.com/rust-lang/cargo/pull/5921) While trying to get that to work, I was reading the implementation for the `vec` function, and I think the following could work and reuse the existing code well.

```rust 
#[cfg(feature = "std")]
impl<T : Strategy> Strategy for Vec<T> {
    type Tree = VecValueTree<T::Tree>;
    type Value = Vec<T::Value>;

    fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
        let max_size = self.len();
        let elements = self.iter().map(|t| t.new_tree(runner)).collect::<Result<Vec<_>, Reason>>()?;

        Ok(VecValueTree {
            elements,
            included_elements: VarBitSet::saturated(max_size),
            min_size: max_size,
            shrink: Shrink::ShrinkElement(0),
            prev_shrink: None,
        })
    }
}

```

Edited to rebase after @AltSysrq's comments on my pr.

I tested a [variation of my cargo pr using](https://github.com/Eh2406/cargo/commit/bdb87b65b1a9990ce466b812692e90af2560aec3) the new functionality insted of using a [.filter to ignore the parts](https://github.com/rust-lang/cargo/pull/5921/files#diff-e4a53852638801c080290c10cd53e3dfR243) that where bad. Shrinking now takes ~1 min with release a vast improvement from the ~1.5 hours it took before (~10 min thanks to @AltSysrq's comments).

**Comment by Centril** [comment]
I was meaning to write up a PR for this but unfortunately I didn't get to it.
Thank you for noting this, and for the perf stats.

I think this would a really great addition.

We should also do this for other data types in `std::collections`:

+ `LinkedList` (possibly by storing the list of strategies internally as a `Vec<T>` for better perf because you know, linked lists are not cache friendly)
+ `VecDeque` (might not need to store this internally as a `Vec<T>`, but might be good for code reuse...)
+ `HashSet` (This would require the set of `Strategy`ies themselves to be `Hash + Eq` which might not be common at least not given BoxedStrategy, but still useful for simpler types such as `Range<..>`).
+ `BTreeSet` (same as with `HashSet`)
+ `HashMap` (presumably the semantics here would be that generating a key and relating it to a generated value but without any forced dependency in the strategies of the keys and values).
+ `BTreeMap` (same as with `HashMap`)
+ `BinaryHeap` (same as with `BTreeSet`)

As for the semantics of `impl<T: Strategy> Strategy for Vec<T>` I think that it should mirror how `impl<T: Strategy, const N: usize> Strategy for [T; N]` works. These semantics are defined [here](https://altsysrq.github.io/rustdoc/proptest/latest/src/proptest/array.rs.html#84). That might even give you better perf than the above.

**Comment by Eh2406** [comment]
I posted this as an issue, not a pr, as I don't feel qualified to discuss the implementation concerns.

For the other types, I don't have a good picture of what I'd expect any of them to do. I feel like it would break the principle of least surprise, no matter what implomantation you give it.

For example if I have a 
```rust
HashMap {
0..=20 => 'a'..='z',
20..=30 => 'A'..='Z',
}
```
What would you expect that to generate?

So my unasked for 2c is hold off on it until you have a clear motivating example of its use. A use that is better than `prop_map` converting to the desired shape.

**Comment by Centril** [comment]
> What would you expect that to generate?

This would generate `HashMap`s of length 2 where:
+ the first element has the key in `0..=20` and value in `'a'..='z'`
+ the second element has the key in `20..=30` and value in `'A'..='Z'`

However, if the first and second elements coincide, then you only get one element.
This can only occur when you have generated the key `20`.
Are there other probable semantics? I can't think of any.

This is the same as for vectors. You can view this as generating for:
```rust
vec![
    (0..=20, 'a'..='z'),
    (20..=30, 'A'..='Z')
}
```
but additionally ensuring that no keys occur twice.

**Comment by AltSysrq** [comment]
> `Vec<impl Strategy>`

While I've increasingly felt that the DRU-style arrays may have been a mistake (for reasons similar to what I'll discuss below), this addition would be consistent with the rest of the API and is probably the most natural way to express it anyway. I can probably add it pretty soon.

> Other collections

DRU-style kind of breaks down with most of the other collection types since, as @Centrial mentioned earlier, you end up with things like needing strategies which are `Hash + Eq` even though you don't plan on using them as lookup keys, and most strategies are neither `Hash` nor `Eq`. It also introduces nondeterminism for `HashMap` and `HashSet` since now proptest would need to iterate those structures and iteration order varies per process.

`LinkedList` and `VecDeque` do not suffer from that problem, but since vanilla rust only has syntax sugar for making `Vec`s, the difference between "Make a `Vec` and turn it into a `LinkedList`" and "Make a `Vec` and pass it to this function to get a `LinkedList` strategy" seems marginal to me.

I can probably get the `Vec` thing added pretty soon.

**Comment by Eh2406** [comment]
> DRU-style

I am not sure what that acronym means, but from context... I do not have a strong preference about whether it is `impl`ed on `Vec` vs. `impl`ed on a new type that is created with a function. Either way works for my needs.

**Comment by Centril** [comment]
> It also introduces nondeterminism for HashMap and HashSet since now proptest would need to iterate those structures and iteration order varies per process.

Ah nicely spotted; Tho it would work for `BTreeMap` and `BTreeSet`.

> LinkedList and VecDeque do not suffer from that problem, but since vanilla rust only has syntax sugar for making Vecs, the difference between "Make a Vec and turn it into a LinkedList" and "Make a Vec and pass it to this function to get a LinkedList strategy" seems marginal to me.

Seems like a good reason to keep it out for now.
Should be pretty trivial to get those types working once you have `Vec`.

> I do not have a strong preference about whether it is impled on Vec vs. impled on a new type that is created with a function.

For consistency with `[S: Strategy; N]` I'd say it should be directly on the `Vec`; this also seems most ergonomic as you get the benefits of the `vec![..]` macro and don't have to route through a newtype.

**Comment by AltSysrq** [comment]
`impl<T : Strategy> Strategy for Vec<T>` is in 0.8.6.

> > DRU-style
> what that acronym means

"Declaration reflects use" , usually used to describe C type syntax.
