### ISSUE TITLE
Consider using `std::panic::set_hook`

### ISSUE THREAD

**Issue by jonas-schievink** [AltSysrq/proptest#90]
The `prop_assert*!` macros basically only exist because a failing `assert!` will print to stderr (at least according to the documentation). This can be disabled by setting a custom panic hook that does not print anything.

**Comment by AltSysrq** [comment]
Original issue: https://github.com/AltSysrq/proptest/issues/3

There are several reasons why I think the `prop_assert` macros do pull their weight:

- `set_hook` is global, so it would interact with other tests in the same process. Since tests are run in parallel, registering at the start of a test and deregistering after doesn't work around the issue.

- There's a use case where the panic messages / backtraces for test assertion failures are not useful, but panics from inside the implementation being tested are.

- The non-panicking macros are absolutely required for nostd environments, where proptest cannot catch panics in order to do shrinking.

**Comment by jonas-schievink** [comment]
Ah I see, that makes sense.
